#!/usr/bin/env bash
set -eu -o pipefail

export GITLAB_API_ENDPOINT=${GITLAB_API_ENDPOINT:-"https://gitlab.com/api/v4"}

orig=$1
new=$2
namespace=$3
project=$4

COMPARE_GIT_WS_ROOT=$(mktemp -d)
cleanup() {
    rm -rf "$COMPARE_GIT_WS_ROOT" || true
    git worktree prune || true
}
trap cleanup EXIT

WORKTREE_PREFIX=cv-$(LC_ALL=C tr -dc 'A-Za-z0-9@%&,.()' </dev/urandom | head -c 8) || true

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

git worktree add "$COMPARE_GIT_WS_ROOT"/"$WORKTREE_PREFIX-orig" "$orig"
git worktree add "$COMPARE_GIT_WS_ROOT"/"$WORKTREE_PREFIX-new" "$new"

(
    cd "$COMPARE_GIT_WS_ROOT"/"$WORKTREE_PREFIX-orig"
    docker build --tag "gl-exporter:$orig" .
)

(
    cd "$COMPARE_GIT_WS_ROOT"/"$WORKTREE_PREFIX-new"
    docker build --tag "gl-exporter:$new" .
)

p_orig_name="project-$project-$orig"
p_new_name="project-$project-$new"

docker run --rm --env GITLAB_API_ENDPOINT --env GITLAB_USERNAME --env GITLAB_API_PRIVATE_TOKEN \
    --volume "$ROOT/shared":/shared --interactive --tty "gl-exporter:$orig" \
    gl_exporter --namespace "$namespace" --project "$project" --out-file "/shared/$p_orig_name.tar.gz"

docker run --rm --env GITLAB_API_ENDPOINT --env GITLAB_USERNAME --env GITLAB_API_PRIVATE_TOKEN \
    --volume "$ROOT/shared":/shared --interactive --tty "gl-exporter:$new" \
    gl_exporter --namespace "$namespace" --project "$project" --out-file "/shared/$p_new_name.tar.gz"

mkdir -p "shared/$p_orig_name" "shared/$p_new_name"
tar -zxvf "shared/$p_orig_name.tar.gz" -C "shared/$p_orig_name"
tar -zxvf "shared/$p_new_name.tar.gz" -C "shared/$p_new_name"

diff -r "shared/$p_orig_name" "shared/$p_new_name"
diff -r "shared/$p_orig_name/log/gl-exporter.log" "shared/$p_new_name/log/gl-exporter.log"
